### PR TITLE
Oracle: booleans are 0 or 1

### PR DESCRIPTION
**Pull request by fhendrikx**
In Oracle there are no false or true. 

Everything is 0 or 1.

### CODE REVIEW

**Comment by siracusa** [comment]
The choice between 0/1 or t/f or something else is arbitrary, and I don't want to break backwards compatibility by changing it at this point.

**Comment by fhendrikx** [comment]
I don't understand... Oracle doesn't use TRUE/FALSE, only 1/0. By making this change, the driver actually works, unlike the current situation, where it fails. Am I maybe missing something here?

**Comment by siracusa** [comment]
Maybe I don't understand what this patch is trying to do. Can you show me a failing test on a real Oracle table?

**Comment by fhendrikx** [comment]
This snippet of code works when using 0 and 1 as boolean values:

```
my $db    = Avenir::Settle::OBJ::DB->new();
my $audit = Avenir::Settle::OBJ::Audit->new(db => $db);
$audit->category(LOG_CAT_NORMAL);
$audit->prio(LOG_INFO);
$audit->action('Test');
$audit->private(1);                   << this is the value in question; true
$audit->save();
```

but switch them back to f and t, and it fails:

```
DBD::Oracle::st execute failed: ORA-01722: invalid number (DBD ERROR: error possibly near <*> indicator at char 260 in 'INSERT INTO settle.audits
(
  id,
  category,
  prio,
  action,
  detail,
  private,
  sessionid,
  username,
  userid,
  orgid,
  objid,
  objtype,
  objversion,
  objdata,
  linkobjid,
  linkobjtype,
  created,
  changed
)
VALUES
(
:p1,
:p2,
:p3,
:p4,
:p5,
:<*>p6,
:p7,
:p8,
:p9,
:p10,
:p11,
:p12,
:p13,
:p14,
:p15,
:p16,
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
)') [for Statement "INSERT INTO settle.audits
(
  id,
  category,
  prio,
  action,
  detail,
  private,
  sessionid,
  username,
  userid,
  orgid,
  objid,
  objtype,
  objversion,
  objdata,
  linkobjid,
  linkobjtype,
  created,
  changed
)
VALUES
(
?,
?,
?,
?,
?,
?,
?,
?,
?,
?,
?,
?,
?,
?,
?,
?,
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
)" with ParamValues: :p1='869', :p10=1, :p11=undef, :p12=undef, :p13=1, :p14=undef, :p15=undef, :p16=undef, :p2=0, :p3=6, :p4='Test', :p5=undef, :p6='t', :p7=undef, :p8=undef, :p9=1] at /usr/local/share/perl5/5.32/Rose/DB/Object.pm line 1103.
```

You will notice that p6 is set to 't', which Oracle rejects, since it doesn't have a boolean type.

**Comment by fhendrikx** [comment]
The column 'private' is defined as boolean in rose:

 `private         => { type => 'boolean', not_null => 1, default => 0 },`

and looks that way too under PostgreSQL:

`private     | boolean                        |           | not null |`


However, under Oracle, it ends up as:

 `PRIVATE				   NOT NULL NUMBER(1)`

**Comment by fhendrikx** [comment]
If you'd prefer a "parallel" oracle driver (with a different name, etc) for these changes, that would make sense too.

**Comment by siracusa** [comment]
Can you post the "audits" table definition?

**Comment by fhendrikx** [comment]
Rose:

`__PACKAGE__->meta->setup(
    table   => 'audits',

    columns => [
        id              => { type => 'bigserial', not_null => 1 },
        category        => { type => 'integer', not_null => 1, default => 0x00 },
        prio            => { type => 'integer', not_null => 1, default => 0x06 },
        action          => { type => 'varchar', length => 64, not_null => 1 },
        detail          => { type => 'varchar', length => 128 },
        private         => { type => 'boolean', not_null => 1, default => 0 },
        sessionid       => { type => 'varchar', length => 192 },
        username        => { type => 'varchar', length => 64 },
        userid          => { type => 'bigint', default => 1 },
        orgid           => { type => 'bigint', default => 1 },
        created         => { type => 'timestamp', not_null => 1, default => 'CURRENT_TIMESTAMP' },
        changed         => { type => 'timestamp', not_null => 1, default => 'CURRENT_TIMESTAMP' },
    ],

    primary_key_columns => [ 'id' ],

    allow_inline_column_values => 1,
`

Oracle SQL:

`     CREATE TABLE audits (id NUMBER(20) NOT NULL, category NUMBER(5) NOT NULL, prio NUMBER(10) NOT NULL, action VARCHAR2(64) NOT NULL, detail VARCHAR2(128) DEFAULT NULL NULL, private NUMBER(1) NOT NULL, sessionId VARCHAR2(192) DEFAULT NULL NULL, username VARCHAR2(64) DEFAULT NULL NULL, userId NUMBER(20) DEFAULT NULL NULL, orgId NUMBER(20) DEFAULT NULL NULL, created TIMESTAMP(0) NOT NULL, changed TIMESTAMP(0) NOT NULL, PRIMARY KEY(id));
`

**Comment by fhendrikx** [comment]
https://stackoverflow.com/questions/3726758/is-there-any-boolean-type-in-oracle-databases

**Comment by siracusa** [comment]
OK, I see the issue. What I was getting at with my first comment is that, given the lack of a "real" boolean column type, what one chooses to use as your stand-in for a boolean column is arbitrary. I chose to use CHAR(1) with a t/f constraint and you chose to use NUMBER(1) with 1/0 values. Neither is more "right" than the other, but the format_boolean() method in Rose::DB is made for CHAR(1)-style "boolean" columns.

**Comment by fhendrikx** [comment]
Given that, it is understandable that you don't want to change your definition. What do you think about a "parallel" oracle driver that uses my 0/1 definition for booleans? I'd be happy to maintain it... ?

**Comment by siracusa** [comment]
How about just a setting within the existing Rose::DB::Oracle driver that toggles between the two behaviors?

(Also, you can always "monkey patch" it by loading the Rose::DB::Oracle module and then overriding the format_boolean() method with the different version in this pull request.)

**Comment by fhendrikx** [comment]
Okay, good idea. I will create a new PR.

**Comment by siracusa** [comment]
Don't forget to add tests and POD documentation.

**Pull request closed without merging**
