### PR TITLE
Closes input-required-attribute

### PR DESCRIPTION
**Pull request by ThisUsedToBeAnEmail**
required is a usefull html attribute that will prevent form submission when a required field does not have a value.

### CODE REVIEW

**Comment by ThisUsedToBeAnEmail** [comment]
A future improvement - add support for oninvalid and oninput that way you will be able to add custom error messages.

<input required oninvalid="this.setCustomValidity('Please Enter valid email')" oninput="setCustomValidity('')" />

**Comment by siracusa** [comment]
The "required" attribute is a boolean attribute, as explained here:

https://www.w3.org/TR/2011/WD-html5-20110405/common-input-element-attributes.html#the-required-attribute

That's why it's in the list of boolean attributes in the code.

**Comment by ThisUsedToBeAnEmail** [comment]
With your existing code 'required' never makes it into the html.

**Comment by siracusa** [comment]
Ah, I see. I think this change needs to be done in a slightly different way. I'm working on it now.

**Comment by siracusa** [comment]
Try this change and let me know if it works for you: https://github.com/siracusa/rose/commit/e03d336c7f8ed27c5fc43bec75234531ee0502da

**Comment by ThisUsedToBeAnEmail** [comment]
looks good to me, thanks.

**Comment by siracusa** [comment]
OK, this change is uploaded to CPAN as 0.626.

**Pull request closed without merging**
