### PR TITLE
Oracle: DSN constructed differently

### PR DESCRIPTION
**Pull request by fhendrikx**
Connecting to a database service using the standard notation; we need the DSN to look a little differently.

This PR keeps backwards compatibility, but isn't necessarily the best approach.

Happy to discuss... or look at alternatives.

### CODE REVIEW

**Comment by siracusa** [comment]
I'm not sure what this patch is intended to do. Adding tests and updated documentation would help.

**Comment by fhendrikx** [comment]
I will look at this again. The patch allows you to connect to a database as a service using the following notation:

$dbh = DBI->connect("dbi:oracle://myhost:1522/ORCL",'username', 'password');

**Comment by fhendrikx** [comment]
However, if I missed something, or there is a better way, please let me know. 

The key outcome is that I can connect to a PDB using the notation above, whereas the older notation doesn't allow  that.

**Comment by fhendrikx** [comment]
For this PR, we need to be able to connect to a service (e.g. pdb1).

These two examples, using DBI both work correctly:
  $dbh = DBI->connect("dbi:Oracle:host=onyx;service_name=pdb1;port=1521","user/test");
  $dbh = DBI->connect("dbi:Oracle://onyx:1521/pdb1","user","test");

Any preferences for how this could be added to the existing build_dns routine?

Thanks

**Comment by siracusa** [comment]
Maybe add a "service" attribute to Rose::DB, then incorporate that attribute in Rose::DB::Oracle's build_dsn() method?

**Pull request closed without merging**
